### ISSUE TITLE
Multiple Clarification Question

### ISSUE THREAD

**Issue by Celepito** [bahalbach/PF2Calculator#20]
It isnt immediately obvious to me how exactly somethings work, sorry for the confusion.

E.g. a Fire Kineticist's Aura Junction does the equivalent of adding 1/2 Level damage to a Fire Impulse as long as it deals damage. Ergo, on a basic save, that would mean the enemy needs to Succeed on the Save, or do worse than that. 
I can represent the damage just fine, with the Static Damage function in a new Damage Line, but I'm not sure which condition I have to use there; is it 'Success or worse' (since the target needs to do worse), or is it 'Success or better' (cause it would be better for me, i.e. "I" succeed better)? Or are these purely for rider effects like from Certain Strike, and dont work for save-based attacks?

And if I want to add that weakness to an Elemental Blast, do I use the 'Success or Better' Condition for that Damage Line, cause my attack has to succeed?

Similarly, the new Dragonblood Heritage's 'Dragon's Breath' can get 'Lingering Breath' at Level 17, which adds persistent damage if the target save crit fails or fails. Do I use 'Fail or worse' for that, or 'Success or better' to represent that?

To make that more clear, may I suggest adding descriptor to that line and clearly stating which state are meant? E.g. instead of 'Fail or worse', make it 'Target Save Fails or Crit Fails'. (Assuming that 'Fail or worse' does indeed mean those two states.)

Then, I'm not sure if there is a difference between 'Create a new Activity' and 'Create a new Child Activity'? As-in, if, within a Routine, is there a difference if I create 3 Activities, one Activity with a Child Activity that chain to another Child Activity, and one Activity with two Child Activities? (I assume the only difference is that I can set a Condition for the Child Activities and from what that condition triggers?)

Which get me to Molten Wire, which is an Attack Roll into a Basic Save if that Roll hits, which I then follow up with an Elemental Blast. 
This is best represented with an Attack Roll Activity, into a Child Activity with 'On Success or Better', and then be a Basic Save itself; 
or should I use 'Add Damage' in the Attack Roll Activity, set that 2nd Damage Line to 'Basic Save' and do it that way? Do I then add another Child Activity with 'Always' onto the initial Attack Roll to represent the Elemental Blast, or do I make it a new Activity straight up? And I definitely dont put it as a Child Activity onto the Save Activity, cause then, even if I set it to 'Always' it would only trigger if the Save was a 'Success or Better', correct? Or would the 'Always' overwrite that?

**Comment by bahalbach** [comment]
Success or worse means success, failure, critical failure.
It works the same for saves or attack rolls
You could use that to represent a weakness, or you could add a weakness to a damage type to the target.

Yes, you can use success or better to represent weakness for an attack roll.

Anther difference for child activities, is if a parent sets something like flat footed on a success, that will only apply to child activities.

If the basic save only happens on a hit, use a child activity

Make a new activity for the elemental blast. Always as a child of the save would not work, always as a child of the roll would, but there's no reason to.
